services:
  db:
    image: postgres:15
    container_name: socratic_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qArshRANA
      POSTGRES_DB: socratic_eye
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  socratic_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socratic_main
    ports:
      - "80:80"
      - "5000:5000"
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data: